# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Python slim
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir mcp[cli] httpx dinero

# Copy application code
COPY . .

# Expose no port (stdio server)
# Default command
CMD ["python", "main.py"]
